# Use root/example as user/password credentials

version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: hydra
    ports:
      - 8080:8080
